spring.application.name=auth-server
server.port=9000

# Demo issuer (override in docker compose)
auth.issuer-uri=${AUTH_ISSUER_URI:http://localhost:9000}

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

logging.level.com.microfocus.example=DEBUG

